import 'dart:typed_data';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import '../models/medical_record.dart';

class MedicalRecordService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseStorage _storage = FirebaseStorage.instance;
  
  Stream<List<MedicalRecord>> getMedicalRecords(String elderlyId) {
    return _firestore
        .collection('medical_records')
        .where('elderlyId', isEqualTo: elderlyId)
        .snapshots()
        .map((snapshot) {
          final records = snapshot.docs
              .map((doc) => MedicalRecord.fromMap(doc.data(), doc.id))
              .where((record) => record.isActive)
              .toList();
          
          records.sort((a, b) => b.uploadDate.compareTo(a.uploadDate));
          return records;
        });
  }

  Future<void> addMedicalRecord({
    required String elderlyId,
    required String title,
    required String description,
    required String hospitalName,
    required String doctorName,
    required DateTime recordDate,
    required String uploadedByRole,
    required Uint8List fileBytes,
    required String fileName,
    required int fileSize,
    required String fileType,
  }) async {
    // 1. Upload to Firebase Storage
    String filePath = 'medical_records/$elderlyId/${DateTime.now().millisecondsSinceEpoch}_$fileName';
    Reference storageRef = _storage.ref().child(filePath);
    
    // Add content type if possible
    SettableMetadata metadata = SettableMetadata(
      contentType: fileType == 'pdf' ? 'application/pdf' : 'image/$fileType',
    );
    
    TaskSnapshot uploadTask = await storageRef.putData(fileBytes, metadata);
    String fileUrl = await uploadTask.ref.getDownloadURL();

    // 2. Save to Firestore
    MedicalRecord record = MedicalRecord(
      id: '', // Will be generated by Firestore
      title: title,
      description: description,
      hospitalName: hospitalName,
      doctorName: doctorName,
      recordDate: recordDate,
      uploadDate: DateTime.now(),
      fileSize: fileSize,
      fileType: fileType,
      fileUrl: fileUrl,
      uploadedByRole: uploadedByRole,
      elderlyId: elderlyId,
      isActive: true,
    );

    await _firestore.collection('medical_records').add(record.toMap());
  }

  Future<void> updateMedicalRecord(String recordId, Map<String, dynamic> data) async {
    await _firestore.collection('medical_records').doc(recordId).update(data);
  }

  Future<void> softDeleteMedicalRecord(String recordId) async {
    await updateMedicalRecord(recordId, {'isActive': false});
  }
}
